### ISSUE TITLE
Update or replace `manifestVersion`

### ISSUE THREAD

**Issue by michaeltlombardi** [PowerShell/DSC#127]
### Summary of the new feature / enhancement

In prior conversations and in the decomposed schema, I have the `manifestVersion` key in the resouce manifest documented as defining the version of the resource manifest schema that the manifest adheres to, requiring it to be semver and limited to the versions of the schema we support, which is currently `1.0`.

A few things:

- `1.0` isn't valid semver by the [regex recommended on semver.org][01] - it would have to be `1.0.0` (and should maybe more accurately be `0.1.0`)
- I thought I remembered there being a check on this version in the code, but a quick check didn't turn one up.
- If this is actually referencing the canonical schema for the manifest, should this maybe just be the `$schema` key and point to the resource manifest schema's `$id`?

[01]: https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string

### Proposed technical implementation details (optional)

Either:

1. Update `manifestVersion` to use a valid semantic version string, like `0.1.0`
2. Replace `manifestVersion` with the `$schema` keyword and require the specified schema to be one of the list of supported schemas.

**Comment by SteveL-MSFT** [comment]
@michaeltlombardi I think using `$schema` is the better option, can you suggest the URL?

**Comment by michaeltlombardi** [comment]
I would recommend the bundled schema for the manifest, which is currently:

```yaml
https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/bundled/resource/manifest.json
```

This will also automatically associate the JSON file with the schema for IntelliSense and hover help (though not the extended authoring schema, which is something we can investigate - same URL, but `manifest.vscode.json`).

I would recommend making the value an enum so we can be forward-thinking about managing schema versions. Also, in the next release, we could mark the `manifestVersion` key as deprecated and indicate they should migrate to using `$schema`, then remove `manifestVersion` in the next release or two.
