### ISSUE TITLE
Support YAML and JSONC for resource manifests

### ISSUE THREAD

**Issue by michaeltlombardi** [PowerShell/DSC#129]
### Summary of the new feature / enhancement

As a DSC Resource author, I want to be able to author and maintain my resource manifests in YAML without needing to convert them to JSON as a build step, because authoring, maintaining, documenting, and reading YAML files is easier for me.

I'd like to be able to author my manifests in either JSONC or YAML so that I can include comments for both local development and maintenance purposes.

### Proposed technical implementation details (optional)

Support discovering DSC Resource manifests if they're in the `PATH` with any of the following file extensions:

- `.dsc.resource.json`
- `.dsc.resource.jsonc`
- `.dsc.resource.yaml`
- `.dsc.resource.yml`

**Comment by SteveL-MSFT** [comment]
WG discussed this to allow resource manifest to be in YAML, but not mix of YAML/JSON in a single file.
