### ISSUE TITLE
Support a `--file` option for `dsc config *` commands

### ISSUE THREAD

**Issue by michaeltlombardi** [PowerShell/DSC#130]
### Summary of the new feature / enhancement

As a user working with DSC Configuration documents, I want to be able to specify the path to a configuration document saved as a file so that I can point DSC to saved files instead of always piping/redirecting the contents of a document to DSC.

For example:

```sh
dsc config test --file ./app.dsc.config.yaml
dsc config test -f ../security/baseline.dsc.config.yaml
```

**Comment by SteveL-MSFT** [comment]
I'll add both `-input` and `-inputFile` parameters.  These will be global, so it'll be before the subcommand.
