### ISSUE TITLE
The `name` key and uniqueness in a document/group

### ISSUE THREAD

**Issue by michaeltlombardi** [PowerShell/DSC#140]
> RE: groups and unique names
> 
> Must names be unique within the *entire* document, including the names defined within groups?  How will DSC know that a third-party group is in fact a group to enforce that?  Or will names be "namespaced" under the name of their containing group, and thus addressable via some form of `group-name/member-name` syntax?
> 
> _Originally posted by @JohnMcPMS in https://github.com/PowerShell/DSC/pull/94#discussion_r1283805579_

**Comment by SteveL-MSFT** [comment]
Current design (which I've been told follows ARM) is that name uniqueness is only required (and currently only validated) within the same peer/sibling group.
