### ISSUE TITLE
Support sending control signals to DSC

### ISSUE THREAD

**Issue by BerheAbrha** [PowerShell/DSC#150]
### Summary of the new feature / enhancement

-  When other agents are invoking DSC and if issued operation need to stop.  It will need a way to send control signal to the child process. 

### Proposed technical implementation details (optional)
Send event to parent process so it can close the process handle. 

WINDOWS
```
API DOC for sending events: - https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createeventa
```
LINUX 
```
https://www.tutorialspoint.com/unix_system_calls/sigaction.htm
```

**Comment by Bpoe** [comment]
Would responding to SIGINT as a request to stop meet the needs?
(https://stackoverflow.com/questions/813086/can-i-send-a-ctrl-c-sigint-to-an-application-on-windows)

**Comment by michaeltlombardi** [comment]
The Rust CLI book has a chapter on [signal handling][01], which points to the [signal_hook][02] crate as an option. 

It looks like the crate currently supports signals fully for not-Windows, and supports a limited subset of signals on windows, notably including `SIGABRT`, `SIGBREAK`, `SIGINT`, and `SIGTERM`.

[01]: https://rust-cli.github.io/book/in-depth/signals.html
[02]: https://docs.rs/signal-hook/latest/signal_hook/#portability

**Comment by jodi-boone** [comment]
Please re-open as we need to ensure child processes are killed as well as parent.
