### ISSUE TITLE
add-path.ps1 uses pwd not script root

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/DSC#152]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Run the script while not in the same folder that the script is in and it will add the pwd not script root in the path.

```powershell
PS C:\Test> C:\dsc\add-path.ps1
Added C:\Test to $env:PATH
```

### Expected behavior

```console
Added C:\dsc to $env:PATH
```

### Actual behavior

```console
Added C:\Test to $env:PATH
```

### Environment data

```PowerShell
7.4-preview4
```

### Version

3.0-alpha1

**Comment by SteveL-MSFT** [comment]
Good catch.  Will fix.
