### ISSUE TITLE
Discovery optimizations

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#173]
### Summary of the new feature / enhancement

Current design always performs a complete discovery, this will need to be changed with the following proposed optimizations:

1. When using `dsc resource get -r <resourceName>` if the <resourceName> is found, we don't continue with discovery.
2. If a config is provided, if a resource provider isn't used, don't call it to do discovery

**Comment by michaeltlombardi** [comment]
A future, but related enhancement - it would be useful to cache resource lookups and reuse the cache (or specifically invalidate it with a command flag). I think caching is likely more useful for providers than for DSC itself, but I can definitely see that as being useful to some degree, especially if you have a lot of resources on a system.

**Comment by anmenaga** [comment]
Additional details that will make some scenarios (like when only using native resources) way faster:
1) resources search is used one dir at a time in %PATH%; if at some point all required resources are found -> abort the search and start the actual operation
2) In every directory from step1 first search native resources, and, if required resource not found, search resource providers in that directory.
