### ISSUE TITLE
Export support for provider-based resources 

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/DSC#183]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Need a way to support Export operation for provider-based resources.

### Expected behavior

```console
NA
```

### Actual behavior

```console
NA
```

### Environment data

```PowerShell
NA
```

### Version

v1

**Comment by SteveL-MSFT** [comment]
Currently, a group resource can indicate it supports `export` within its resource manifest, but we haven't defined what the output would look like so it can be passed back to `set`.
