### ISSUE TITLE
DSC command completion

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/DSC#186]
### Summary of the new feature / enhancement

As a user I would like the `dsc` executable to generate completions so that shells can use that in their tab completion.

### Proposed technical implementation details (optional)

WinGet supports this feature with a `complete` sub-command: https://learn.microsoft.com/en-us/windows/package-manager/winget/tab-completion

**Comment by michaeltlombardi** [comment]
It looks like the [`clap_complete` crate][01] could serve this purpose.

[01]: https://docs.rs/clap_complete/latest/clap_complete/

**Comment by SteveL-MSFT** [comment]
I've played with `clap_complete` before so it wouldn't be too difficult to add it keeping in mind it generates a shell script you'd run to register the completer.
