### ISSUE TITLE
Support wildcards for get/set/test operations

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/DSC#247]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Currently only list operation supports wildcards:
`dsc resource list test*`

Other operations do not support this currently and end up with 'resource not found' error.
Also need to define what that would mean for `get/set/test/...` operations... doing the operation with the same input on all resource types that match the wildcard?

### Expected behavior

```console
NA
```

### Actual behavior

```console
NA
```

### Environment data

```PowerShell
NA
```

### Version

v1

**Comment by michaeltlombardi** [comment]
I'm not sure we _should_ support non-deterministic resource operations, _especially_ for `set`. Searching for a resource is less impactful than calling the operation for a resource.

**Comment by SteveL-MSFT** [comment]
Seems dangerous to allow executing an operation against a wildcard resource.
