### ISSUE TITLE
VT100 codes are displayed in some cases

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/DSC#273]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Run "dsc resource list" on Windows Server 2022.

![Srv2022](https://github.com/PowerShell/DSC/assets/11860095/ffe41bc3-5716-4a0f-8327-9c36d1a30570)

### Expected behavior

```console
N/A
```

### Actual behavior

```console
N/A
```

### Environment data

```PowerShell
N/A
```

### Version

3.0.0-alpha.4

**Comment by SteveL-MSFT** [comment]
@anmenaga can you confirm this repros with main branch?

**Comment by SteveL-MSFT** [comment]
I think this is due to issue in Server 2022 conhost.  Doesn't repro on Win11 conhost with cmd
