### ISSUE TITLE
Allow DSC/PowerShellGroup to have additional module paths

### ISSUE THREAD

**Issue by msftrubengu** [PowerShell/DSC#285]
### Summary of the new feature / enhancement

By default, winget configure installs PowerShell modules under %LOCALAPPDATA%\Microsoft\WinGet\Configuration\Modules. This was done to avoid conflicts when OneDrive moves the user's profile to their OneDrive's profile while winget configure is executing. If the modules are stored in the winget location powershellgroup.resource.ps1 won't be able to find the modules.

### Proposed technical implementation details (optional)

A new property in the PowerShellGroup with additionalModulePaths

**Comment by anmenaga** [comment]
This scenario should be already working by setting `PSModulePath` env var on `dsc` process.
`PowerShell` process, started by `dsc` will inherit it and will use that to lookup PS modules with DSC resources.
Just remember that `PSDesiredStateConfiguration` module should also be accessible by the value of `PSModulePath` env var that you're setting.

**Comment by SteveL-MSFT** [comment]
Setting the env var seems reasonable we would just document it as the suggested use if the default PSModulePath isn't sufficient.
