### ISSUE TITLE
Expose `delete` as a direct dsc resource operation

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#290]
### Summary of the new feature / enhancement

It may be simpler for DSC resource implementations to implement `delete` rather than have logic as part of `set` to handle `_exist`.  We can still support `_exist` as a special keyword in configuration where `dsc` knows to call `delete` if implemented.

PowerShell resources already implement `ensure` differently, so that won't change either way.

**Comment by michaeltlombardi** [comment]
I'm not sure about this - it does move a little bit away from the underlying state management model of an instance + properties - if you have `delete`, why not `create` (don't update if exist) or `modify` (don't create if not exist)?

It seems like the sort of thing I might expect a higher order tool to implement, rather than a resource or DSC itself.

**Comment by SteveL-MSFT** [comment]
@michaeltlombardi the idea is that this can simplify resource authoring as you can have clear separation of `set` (CreateOrUpdate) and `delete` whereas, for example, in the registry resource, I basically have a bunch of `if` statements to check if `_exist` is passed in and it would simplify the code by having `delete` a separate code path.  For end users, they can call `delete` directly via `dsc resource delete ...`, but if using config, it would be abstracted so deletes can occur with create/update within the same config.

**Comment by SteveL-MSFT** [comment]
We should allow resources to implement `_exist` directly, but if the resource implements `delete` then `dsc` will use that to handle `_exist` rather than passing that to the resource.

**Comment by SteveL-MSFT** [comment]
Discussed with @mgreenegit and we agreed to move forward with this proposal
