### ISSUE TITLE
Add `Methods` to table view for `dsc resource list`

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#309]
### Summary of the new feature / enhancement

It would be useful to config authors to see what methods `get`, `set`, `test`, `export` are supported by a resource within the table view

**Comment by michaeltlombardi** [comment]
Are there any resources that can't support `get`? Any resource that supports `get` supports `test` (either directly implemented or synthetic through DSC), I think.

**Comment by tgauth** [comment]
I don't think there's any that don't support `get` because it's a required field in the resource manifest but not sure about `test` as that's still an optional field in the resource manifest

**Comment by michaeltlombardi** [comment]
Even when a resource doesn't implement the `test` command, DSC is able to use [synthetic testing][01] to compare the actual state to the desired state:

> When this property isn't defined, DSC uses a synthetic test method for the resource. The synthetic test method:
>
> 1. Gets the actual state of the instance using the resource's `get` method.
> 1. Compares every defined property of the instance's desired state to the actual state.
> 1. If the desired state of a property isn't equal to the actual state of that property, DSC reports that the instance isn't in the desired state.
>
> Because the synthetic test only checks for equivalency, it can't accurately test resources with properties that can't be evaluated with equivalency alone. For example, if a resource manages package versions and allows setting the version to `latest`, DSC would report an instance with a version of `3.1.0` as being out of the desired state, even if `3.1.0` is the latest version of the package.

[01]: https://learn.microsoft.com/powershell/dsc/reference/schemas/resource/manifest/test?view=dsc-3.0#description

**Comment by SteveL-MSFT** [comment]
I think the intent of this right now is to simply expose what the resource advertises it implements.  So I would expect it to show `get`, `set`, `test`, and/or `export`.  Although `get` is currently mandatory, that may or may not change in the future and I think it would be confusing ot users to not see it shown.  Similarly, although dsc will synthesize `test`, I think it makes sense to show whether the resource implements it directly and it's via docs that indicate `test` is available even if the resource doesn't directly implement it as it does have limitations (direct comparison).
