### ISSUE TITLE
Standardize built-in resource namespaces

### ISSUE THREAD

**Issue by michaeltlombardi** [PowerShell/DSC#324]
### Summary of the new feature / enhancement

Currently, the built-in DSC Resources are named `DSC/<ResourceName>`, like `DSC/AssertionGroup`. To align with the [namespace guidance][01], we should plan to rename these resources to indicate ownership. It would also be useful to identify them as being core or built-in resources that are only upgradeable with DSC itself.

### Proposed technical implementation details (optional)

I propose changing the resource namespaces to one of the following:

- [ ] `Microsoft.DSC.BuiltIn`
- [ ] `Microsoft.DSC`

This would make the AssertionGroup resource either `Microsoft.DSC.BuiltIn/AssertionGroup` or `Microsoft.DSC/AssertionGroup`.

**Comment by SteveL-MSFT** [comment]
The built-in groups will be named:

- Microsoft.DSC/Grouo
- Microsoft.DSC/Assertion
- Microsoft.DSC/Parallel
