### ISSUE TITLE
PowerShell-Adapter should cache resources to disk

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#371]
### Summary of the new feature / enhancement

PowerShell-Adapter should cache the discovered resources to disk so it doesn't have to perform a full discovery each time which is the main perf bottleneck.

### Proposed technical implementation details (optional)

Probably just save the cache as a JSON file somewhere under the user data path:

- Keep last modified date of segments of PSModulePath and modules so if any change, it can just do discovery for those segments rather than full
- If PSModulePath changes from last discovery, may be better to rebuilt cache rather than trying to discover new parts and throw away old ones
- Keep only relevant info which is likely the module that contains the PS resources.  Not sure if there is big perf or functional impact to cache the resources themselves in addition to the module.

**Comment by anmenaga** [comment]
Fixed in #432
