### ISSUE TITLE
Linux release asset is incorrectly suffixed with the .gz extension

### ISSUE THREAD

**Issue by NGPixel** [PowerShell/DSC#443]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Summary

The latest release asset for linux is incorrectly marked as "tar.gz" even though it is not gzipped. The extension should be just ".tar" to avoid confusion while attempting to extract the tarball.

### Steps to reproduce

1. Download either the [DSC-3.0.0-preview.7-x86_64-unknown-linux-gnu.tar.gz](https://github.com/PowerShell/DSC/releases/download/v3.0.0-preview.7/DSC-3.0.0-preview.7-x86_64-unknown-linux-gnu.tar.gz) or the [DSC-3.0.0-preview.7-aarch64-unknown-linux-gnu.tar.gz](https://github.com/PowerShell/DSC/releases/download/v3.0.0-preview.7/DSC-3.0.0-preview.7-aarch64-unknown-linux-gnu.tar.gz) asset files.
2. Attempt to extract with `tar -xzf`
3. Extract fails because tarball is not gzipped.

### Expected behavior

```console
Linux asset files should end with ".tar" and not "tar.gz".
```

### Actual behavior

```console
Linux asset files currently ends in "tar.gz".
```

### Error details

```console
N/A
```

### Environment data

```PowerShell
N/A
```

### Version

v3.0.0-preview.7

### Visuals

N/A

**Comment by SteveL-MSFT** [comment]
This will be fixed with next release
