### ISSUE TITLE
Remove static validation of input

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#490]
### Summary of the new feature / enhancement

Now that we have more functions implemented, many of them can only be resolved at runtime like `reference()` and `parameter()` (and in the future `variable()`).  As such, this breaks static validation as the expression and function needs to be resolved first, but you can only do that at execution time.

This fundamental issue breaks one of the current designs of `dsc.exe` which is to perform static validation and fail before execution.  Instead, we should remove the code that attempts to perform static validation and leave validation to happen at runtime.  The unfortunate result is that you can process a portion of a configuration before failing validation, but the current design simply won't work for real world configurations that depend on expressions.

**Comment by michaeltlombardi** [comment]
I _think_ we should be able to have limited validation, with some values deferred - and for use cases where folks have very complex configurations with a lot of references to outputs from other resources, they _should_ be running with in what-if mode before enforcing a new configuration on a machine.

I think there's still fairly high value in fail-as-soon-as-possible (you specified an invalid static value in the configuration for a resource property) that we shouldn't drop. I think we could just defer function values until runtime and document that behavior.

And just to be clear, this is about _configuration_ validation, we're still pre-validating the resource instance data before invoking a resource, correct?

**Comment by SteveL-MSFT** [comment]
The current design is:

- Static validate configuration (this stays)
- Static validate resources within the configuration (this will change)

Best effort or partial validation could result in surprises to the user (like if the property value is an expression, we just accept it and have it fail at runtime anyways).

Perhaps in the interim, instead of just removing the validation, we can have it as warning messages.

**Comment by michaeltlombardi** [comment]
Warning messages would be useful, I think.

What does the static configuration validation cover? Is it everything except for the `properties` passed to resource instances?

I think we should _definitely_ add a note to the documentation for the `set` command to strongly recommend always running with `--what-if` once when defining or updating a configuration document, and _especially_ when using configuration functions. We can call out the risks around runtime-errors they raise and how running with what-if ensures that you catch any runtime errors from improperly defined configuration functions without changing the system state.

And it would go into the eventual best practices doc as well.

For the VS Code extension, it might be useful to have a "Validate" command actually run a what-if for the document and then report any issues it raises.
