### ISSUE TITLE
Better error message when no input is provided to PowerShell adapters

### ISSUE THREAD

**Issue by Gijsreyn** [PowerShell/DSC#516]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Summary

Executing: `dsc resource get --resource Microsoft.DSC/PowerShell` throws an error "Exception calling "Invoke" with "2" argument(s): "Conversion from JSON failed with error: Unexpected character encountered while parsing value: @. Path '', line 0"

### Steps to reproduce

dsc resource get --resource Microsoft.DSC/PowerShell

### Expected behavior

```console
Message indicating the issue.
```

### Actual behavior

```console
Exception calling "Invoke" with "2" argument(s): "Conversion from JSON failed with error: Unexpected character encountered while parsing value: @. Path '', line 0
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

dsc 3.0.0-preview.8

**Comment by anmenaga** [comment]
This should be fixed in dsc RUST engine like "non-List operations on adapters should be blocked and result in error".

**Comment by Gijsreyn** [comment]
Then my review can be closed and PR can be abonded.
