### ISSUE TITLE
Implement `variables` support

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#56]
### Summary of the new feature / enhancement

Enable config to define and pass variables.  Need to figure out how this is passed to group resources.

**Comment by mgreenegit** [comment]
Here is an example to consider
https://github.com/Azure/azure-quickstart-templates/blob/3d8a68489ff6d8f0420183501a9c16d38bc45cdd/demos/vmss-win-iis-app-ssl/dsc/serviceDSCVMSS.ps1#L143

**Comment by SteveL-MSFT** [comment]
This was fixed via https://github.com/PowerShell/DSC/pull/511
