### ISSUE TITLE
Make merge to main upload the build(s) as artifacts

### ISSUE THREAD

**Issue by michaeltlombardi** [PowerShell/DSC#58]
### Summary of the new feature / enhancement

As an engineer interested in experimenting with `dsc` locally, I want to be able to download the latest build for the project instead of needing to setup my local development environment for Rust and this project.

### Proposed technical implementation details (optional)

The [Rust workflow][01] already builds and tests the code for multiple platforms. With the [`actions/upload-artifact`][02] GitHub Action, the same workflow could also save the built binaries so that interested parties could download archives containing the artifacts.

We could document how to retrieve the artifacts from GitHub until we have a more reliable and friendly way to let people experiment with the applications.

[01]: https://github.com/PowerShell/DSC/blob/main/.github/workflows/rust.yml
[02]: https://github.com/actions/upload-artifact

**Comment by SteveL-MSFT** [comment]
This need replaced by release pipeline
