### ISSUE TITLE
Failure to parse a single resource.json should Not abort resource enumeration

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/DSC#67]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Create a .resource.json with non-compliant syntax, then run:
dsc.exe resource list

### Expected behavior

```console
all valid resources are listed;
```

### Actual behavior

```console
PS C:\DSCv3> dsc.exe resource list                                         
Error: Manifest: C:\DSCv3\bin\debug\testresource.resource.json
JSON: unknown field `customfield`, expected one of `manifestVersion`, `type`, `version`, `description`, `get`, `set`, `test`, `validate`, `provider`, `exitCodes`, `schema` at line 6 column 27
```

### Environment data

```PowerShell
any
```

### Version

1.0

**Comment by mgreenegit** [comment]
Fixed
