### ISSUE TITLE
Handle `WhatIf`

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#70]
### Summary of the new feature / enhancement

Need to have resources support this to work completely

**Comment by dkattan** [comment]
I think there should be a separate stream with WhatIfMessages and in the absence of a Test implementation and Set implements SupportsShouldProcess, Test would call Set with -WhatIf, capture the WhatIfMessages and if any exist (indicating that something needs to get done) then return false.

I also think it would be nice if WhatIfMessages themselves could contain a compliant boolean so that as the set goes through what it _would_ do, you can get positive compliance messages instead of the presence of a WhatIf message indicating non-compliance but not indicating to the user what items _are_ compliant.

**Comment by michaeltlombardi** [comment]
@dkattan trying to rephrase your comment to avoid PowerShell-specific implementation details:

1. Resources should be able to emit structured messages that indicate what a resource would change during a `set` operation.
2. Those messages should describe the change, like `setting property 'foo' from 'bar' to 'baz'`, and include boolean value where `true` indicates that the property is already in the desired state and `false` indicates that it isn't.
3. That those messages in `set` running in this non-apply mode (what-if, noop, whatever it gets called) could be an alternative to relying on DSC's synthetic test, where any `false` value in a message indicates that the resource instance is out of the desired state.

> My experience is that Test and Set generally share a lot of code and look similar. Doing this would prevent the need for code duplication in the Test.

In v3 the implementation for the `test` operation is only required when the resource's properties can't be evaluated with a case-insensitive equivalency check (DSC's built-in synthetic test). If a resource doesn't define `test`, DSC handles it for them.

Specifically regarding the code duplication problem, I've updated the PowerShell documentation for authoring class-based resources such that [the `Test()` method always calls `Get()`][01] and [the `Set()` method always calls `Test()`][02]. The duplication of code across get/set/test is an anti-pattern. The new tutorial for [implementing a command-based DSC Resource in Go][03] doesn't implement `test` at all, but does include logic in the [`set` command][04] for only changing state if changes need to be made.

[01]: https://learn.microsoft.com/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0#the-test-method
[02]: https://learn.microsoft.com/powershell/dsc/tutorials/create-class-based-resource?view=dsc-2.0#the-set-method
[03]: https://powershell.github.io/DSC-Samples/tutorials/first-resource/go/
[04]: https://powershell.github.io/DSC-Samples/tutorials/first-resource/go/5-implement-set

**Comment by michaeltlombardi** [comment]
> I'm a little concerned it will be confused with PowerShell [whatif](https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-shouldprocess?view=powershell-7.3). Maybe we should call it by a different name?

Alternatives used by other tools include:
- Puppet as a [noop mode][01], set with the `--noop` flag or `noop` metaparameter in an instance definition.
- Ansible has a [check mode][02], set with the `--check` flag or `check_mode` in a playbook.
- Chef has a [why-run mode][03], set with the `--why-run` flag, though Chef recommends _not_ using it, as described in their blog post [_Why "Why-Run" Mode Is Considered Harmful_ by Julian Dunn][04] - essentially, that it isn't an effective tool for validating what a run will do or a substitute for compliance validation.
- Salt has both a [test and mock state][05] that don't execute changes.
- Terraform has a [plan command][06] to show what an `apply` will do.
- Pulumi has a [preview command][07] to show what an `up` will do.

Of these options, I think the semantics of `preview` are most aligned with `whatIf` - though it's worth noting that ARM does have the [what-if][08] functionality itself, so reusing that semantic seems okay to me. I do like the combination of having both a `--what-if` flag and `--confirm` flag, the latter showing the what-if output per-resource and prompting for a continuation.

It might be worth defining both `whatIf` and `confirm` boolean options for the resource, borrowing from Puppet and Ansible to have a per-resource alternate behavior:

```yaml
resources:
  - name:   Only show what-if
    type:   Microsoft.Windows/Registry
    whatIf: true
    properties:
      keyPath:    HKCU\tailspin\updates
      valueName:  automatic
      valuData: { String: enable }
  - name:    Show what-if, prompt to enforce
    type:    Microsoft.Windows/Registry
    confirm: true
    properties:
      keyPath:    HKCU\tailspin\updates
      valueName:  automatic
      valuData: { String: enable }
```

I would expect:

- `confirm: true` to supercede `whatif: false`
- Both to _default_ to `false` for an instance declaration
- `--confirm` and `--what-if` to apply to _every_ instance - probably overriding any explicit `confirm: false` or `whatIf: false` settings for instances.

[01]: https://www.puppet.com/docs/puppet/8/configuration.html#noop
[02]: https://docs.ansible.com/ansible/2.9/user_guide/playbooks_checkmode.html
[03]: https://docs.chef.io/ctl_chef_client/#about-why-run-mode
[04]: https://www.chef.io/blog/why-why-run-mode-is-considered-harmful
[05]: https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.state.html
[06]: https://developer.hashicorp.com/terraform/cli/commands/plan
[07]: https://www.pulumi.com/docs/cli/commands/pulumi_preview/
[08]: https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-what-if?tabs=azure-powershell

**Comment by SteveL-MSFT** [comment]
For now, we can focus on `whatif` and leave `confirm` as a separate feature.

For the implementation, we have a `Context` struct which can be reused for this.  Add a member to track `whatif` execution and pass it along so that each invocation knows to emit info rather than perform actual execution.

We can also defer resource participation as I think it will depend on https://github.com/PowerShell/DSC/issues/218 which will expose a pattern to pass optional args to exes to indicate `whatif`.
