### ISSUE TITLE
`resource set` errors unexpectedly when `test` is undefined and `set.preTest` isn't explicitly `true` in resource manifest

### ISSUE THREAD

**Issue by michaeltlombardi** [PowerShell/DSC#86]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

When implementing a command-based DSC Resource without explicitly defining `test`, the `dsc resource set` command errors when the `preTest` key is undefined or is set to `false` in the resource manifest's `set` property.

`dsc resource get` and `dsc resource test` both work as expected.

I discovered this when working with the example implementations in #85.

This is the snippet of the resource manifest with the schema trimmed for readability:

```json
{
    "manifestVersion": "1.0",
    "type": "TSToy.Example/gotstoy",
    "version": "0.1.0",
    "description": "The go implementation of a DSC Resource for the fictional TSToy application.",
    "get": {
        "executable": "gotstoy",
        "args": ["get"],
        "input": "stdin"
    },
    "set": {
        "executable": "gotstoy",
        "args": ["set"],
        "input": "stdin",
        "preTest": false,
        "return": "state"
    },
    "schema": {}
}
```

When `preTest` is removed, the command returns the same error. When `preTest` is set to `true`, the command runs without an error, but also without validating the state beforehand.

### Expected behavior

```console
Either of the following:

1. DSC calls the resource's `set` command if DSC's synthetic `test` for the resource indicates that the resource isn't in the desired state
1. DSC calls the resource's `set` command without checking if the resource is in the desired state.
```

### Actual behavior

```console
DSC returns the error message:


Error: Not implemented: test
```

### Environment data

```PowerShell
N/A
```

### Version

(build from main)

**Comment by SteveL-MSFT** [comment]
This was fixed via https://github.com/PowerShell/DSC/commit/d817869ae5ab7ddd2169c5efd0bb7199512268ec
