### ISSUE TITLE
Implement InputKind Env

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DSC#98]
### Summary of the new feature / enhancement

InputKind = `Args` is intended for simple cases like `bash script resource` where a flat JSON schema would result as name/value pairs sent as parameters and parameter values to the script:

```json
{
  "property1": 1,
  "property2": "hello"
}
```

Would result in:

```console
yourresource -property1 1 -property2 "hello"
```

**Comment by SteveL-MSFT** [comment]
Was thinking about this and looked up how to parse args in Bash.  It's actually quite complicated and requires not obvious code.  Like batch files, it's more optimized for positional parameters.  Instead, it's much easier to deal with env vars.  So I'm changing this to passing input as named env vars.

**Comment by michaeltlombardi** [comment]
Should we not support _both_? Or are we prioritizing env vars now and args later?

**Comment by SteveL-MSFT** [comment]
We can add args support when a use case comes up
